-- CreateTable
CREATE TABLE "USUARIOS" (
    "CODIGO" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "USUARIO" TEXT NOT NULL,
    "CODCLI" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "NIVEL_ACESSO" INTEGER NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" TEXT NOT NULL,

    CONSTRAINT "USUARIOS_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "ENTIDADE" (
    "CODCLI" TEXT NOT NULL,
    "NOME" TEXT NOT NULL,
    "CNPJ" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "ENDERECO" TEXT NOT NULL,
    "CIDADE" TEXT NOT NULL,
    "BAIRRO" TEXT NOT NULL,
    "NUMERO" TEXT NOT NULL,
    "UF" TEXT NOT NULL,
    "FUNCAO" TEXT NOT NULL,
    "PAIS" TEXT NOT NULL,
    "COMPLEMENTO" TEXT NOT NULL,
    "CEP" TEXT NOT NULL,
    "TIPO" TEXT NOT NULL,
    "STATUS" TEXT NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_ENTIDADE" TEXT NOT NULL,

    CONSTRAINT "ENTIDADE_pkey" PRIMARY KEY ("ID_ENTIDADE")
);

-- CreateTable
CREATE TABLE "MAQUINA" (
    "CODIGO" TEXT NOT NULL,
    "DESCRICAO" INTEGER NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_MAQUINA" TEXT NOT NULL,

    CONSTRAINT "MAQUINA_pkey" PRIMARY KEY ("ID_MAQUINA")
);

-- CreateTable
CREATE TABLE "REPRESEN" (
    "CODREP" TEXT NOT NULL,
    "NOME" INTEGER NOT NULL,
    "CODCLI" INTEGER NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_REPRESEN" TEXT NOT NULL,

    CONSTRAINT "REPRESEN_pkey" PRIMARY KEY ("ID_REPRESEN")
);

-- CreateTable
CREATE TABLE "PRODUTOS" (
    "CODIGO" TEXT NOT NULL,
    "DESCRICAO" TEXT NOT NULL,
    "PRECO" TEXT NOT NULL,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_PRODUTO" TEXT NOT NULL,

    CONSTRAINT "PRODUTOS_pkey" PRIMARY KEY ("ID_PRODUTO")
);

-- CreateTable
CREATE TABLE "RECEBER" (
    "NUMERO" TEXT NOT NULL,
    "CODCLI" INTEGER NOT NULL,
    "CODREP" BOOLEAN NOT NULL DEFAULT true,
    "VALOR_TOTAL" TEXT,
    "PARCELA" TEXT,
    "VALOR_PARCELA" TEXT,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_RECEBER" TEXT NOT NULL,

    CONSTRAINT "RECEBER_pkey" PRIMARY KEY ("ID_RECEBER")
);

-- CreateTable
CREATE TABLE "RECEBERB" (
    "NUMERO" TEXT NOT NULL,
    "CODCLI" INTEGER NOT NULL,
    "CODREP" BOOLEAN NOT NULL DEFAULT true,
    "VALOR_PAGO" TEXT,
    "PARCELA" TEXT,
    "VALOR_PARCELA" TEXT,
    "DT_PAGAMENTO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_RECEBERB" TEXT NOT NULL,

    CONSTRAINT "RECEBERB_pkey" PRIMARY KEY ("ID_RECEBERB")
);

-- CreateTable
CREATE TABLE "PAGAR" (
    "NUMERO" TEXT NOT NULL,
    "CODCLI" INTEGER NOT NULL,
    "CODREP" BOOLEAN NOT NULL DEFAULT true,
    "VALOR_TOTAL" TEXT,
    "PARCELA" TEXT,
    "DT_VENCIMENTO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_CADASTRO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "DT_ALTERACAO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_PAGAR" TEXT NOT NULL,

    CONSTRAINT "PAGAR_pkey" PRIMARY KEY ("ID_PAGAR")
);

-- CreateTable
CREATE TABLE "PAGARB" (
    "NUMERO" TEXT NOT NULL,
    "CODCLI" TEXT NOT NULL,
    "CODREP" TEXT NOT NULL,
    "VALOR_TOTAL" TEXT,
    "VALOR_PAGO" TEXT,
    "PARCELA" TEXT,
    "DT_PAGAMENTO" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "ID_PAGARB" TEXT NOT NULL,

    CONSTRAINT "PAGARB_pkey" PRIMARY KEY ("ID_PAGARB")
);
